### ISSUE TITLE
[1.7.10] Server Crash (Attempted to load class bje for invalid side SERVER)

### ISSUE THREAD

**Issue by aking4125** [FalsePattern/EndlessIDs#2]
Hello,

When attempting to run EndlessIDs either 1.1.0 or 1.2.0 on a server. The server crashes with this log file generated. 
[fml-server-latest.log](https://github.com/FalsePattern/EndlessIDs/files/8535467/fml-server-latest.log)

Removing EndlessIDs and using NotEnoughIDs works. Any ideas?

**Comment by FalsePattern** [comment]
Fixed in 1.2.1

**Comment by aking4125** [comment]
While the error `Attempted to load class bje for invalid side SERVER` is no longer there. The server is still crashing with EndlessIDs. 

Again, removing this and using NotEnoughIDs works.

[fml-server-latest.log](https://github.com/FalsePattern/EndlessIDs/files/8535898/fml-server-latest.log)

**Comment by aking4125** [comment]
Copy that. [Uploaded using Mediafire](https://www.mediafire.com/file/nszpilvm93tl2ax/Epic_Marvels_1_V13.7z/file). Give it a look.

**Comment by FalsePattern** [comment]
It's a complex interaction between pure ASM and Mixins that causes this crash, it's fixable by adding Mixingasm to the pack: https://github.com/makamys/Mixingasm

**Comment by aking4125** [comment]
Well. Complex indeed. This did work. 

Sorry for the complicated issue. Thank you for your support.
